import type { StoreShape } from "./types";

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();
const daysFrom = (d: number) => new Date(now + d * 86400000).toISOString();

export const DEMO_RESTAURANT_ID = "rest_golden_gate_bistro";
export const DEMO_ORG_ID = "org_arena_demo";
export const DEMO_USER_ID = "user_demo_owner";

export function createInitialStore(): StoreShape {
  return {
    demoMode: true,
    activeRestaurantId: DEMO_RESTAURANT_ID,
    activeUserId: DEMO_USER_ID,
    restaurants: [
      {
        id: DEMO_RESTAURANT_ID,
        orgId: DEMO_ORG_ID,
        name: "Golden Gate Bistro",
        slug: "golden-gate-bistro",
        cuisine: "California Contemporary",
        city: "Oakland",
        state: "CA",
        timezone: "America/Los_Angeles",
        brandVoice:
          "Warm, local, slightly elevated. Celebrate Bay Area ingredients, community, and approachable luxury. Never corporate-sounding.",
        brandColors: { primary: "#ea580c", secondary: "#0f172a" },
        locations: 2,
        website: "https://example.com/golden-gate-bistro",
        phone: "(510) 555-0142",
        createdAt: daysAgo(120),
      },
    ],
    users: [
      {
        id: "user_platform_admin",
        email: "admin@restaurant-os.demo",
        name: "Sam Admin",
        role: "platform_admin",
        portal: "admin",
        restaurantIds: [], // all restaurants
      },
      {
        id: DEMO_USER_ID,
        email: "owner@goldengatebistro.demo",
        name: "Alex Rivera",
        role: "owner",
        portal: "client",
        restaurantIds: [DEMO_RESTAURANT_ID],
      },
      {
        id: "user_marketer",
        email: "marketing@goldengatebistro.demo",
        name: "Jordan Lee",
        role: "marketer",
        portal: "client",
        restaurantIds: [DEMO_RESTAURANT_ID],
      },
      {
        id: "user_viewer",
        email: "viewer@goldengatebistro.demo",
        name: "Casey View",
        role: "viewer",
        portal: "client",
        restaurantIds: [DEMO_RESTAURANT_ID],
      },
    ],
    tickets: [
      {
        id: "tkt_001",
        restaurantId: DEMO_RESTAURANT_ID,
        restaurantName: "Golden Gate Bistro",
        createdBy: "Alex Rivera",
        priority: "high",
        category: "integrations",
        subject: "Need Meta Ads connected before brunch campaign",
        body: "We launch BRUNCH15 Friday. Please verify Instagram + Meta Ads tokens and confirm publish path.",
        status: "open",
        assignee: "Sam Admin",
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
      },
      {
        id: "tkt_002",
        restaurantId: DEMO_RESTAURANT_ID,
        restaurantName: "Golden Gate Bistro",
        createdBy: "Jordan Lee",
        priority: "medium",
        category: "ai",
        subject: "Claude captions preferred for brand voice",
        body: "Demo AI is fine for drafts but we want Anthropic for final IG captions. Need keys on Vercel.",
        status: "in_progress",
        assignee: "Sam Admin",
        createdAt: daysAgo(2),
        updatedAt: daysAgo(0.5),
      },
    ],
    content: [
      {
        id: "cnt_001",
        restaurantId: DEMO_RESTAURANT_ID,
        title: "Weekend Brunch Drop",
        body: "Fog outside. Sunshine on your plate. ☀️ Our weekend brunch is back with lemon ricotta pancakes, smoked salmon boards, and bottomless local cold brew. Reserve your spot — walk-ins welcome after 11.",
        hashtags: ["#OaklandEats", "#BayAreaBrunch", "#GoldenGateBistro", "#SupportLocal"],
        platforms: ["instagram", "facebook", "google_business"],
        status: "scheduled",
        mediaUrls: [],
        mediaType: "image",
        scheduledAt: daysFrom(1),
        createdBy: "Alex Rivera",
        aiGenerated: true,
        offerId: "off_brunch15",
        createdAt: daysAgo(2),
        updatedAt: daysAgo(1),
      },
      {
        id: "cnt_002",
        restaurantId: DEMO_RESTAURANT_ID,
        title: "Loyalty Double Points",
        body: "Members: this week your points work overtime. Earn 2× on every entrée Mon–Thu. Stack with your birthday reward if it’s your month. Open the app or mention your number at the host stand.",
        hashtags: ["#LoyaltyRewards", "#OaklandFood", "#MemberPerks"],
        platforms: ["instagram", "email", "sms"],
        status: "pending_approval",
        mediaUrls: [],
        mediaType: "none",
        createdBy: "AI Studio",
        aiGenerated: true,
        offerId: "off_2xpoints",
        createdAt: daysAgo(0.5),
        updatedAt: daysAgo(0.5),
      },
      {
        id: "cnt_003",
        restaurantId: DEMO_RESTAURANT_ID,
        title: "Chef’s Seasonal Pasta",
        body: "New on the dinner menu: hand-cut pappardelle with roasted squash, brown butter, sage, and toasted hazelnuts. Limited run while the farmers’ market haul lasts.",
        hashtags: ["#SeasonalMenu", "#PastaNight", "#FarmToTable"],
        platforms: ["instagram", "facebook", "tiktok"],
        status: "approved",
        mediaUrls: [],
        mediaType: "video",
        createdBy: "Jordan Lee",
        approvedBy: "Alex Rivera",
        aiGenerated: false,
        createdAt: daysAgo(3),
        updatedAt: daysAgo(2),
      },
      {
        id: "cnt_004",
        restaurantId: DEMO_RESTAURANT_ID,
        title: "Happy Hour — Downtown",
        body: "Weekday happy hour 4–6pm downtown: $8 house cocktails, half-off small plates, and free wifi that actually works. Bring your laptop or your crew.",
        hashtags: ["#HappyHour", "#DowntownOakland", "#AfterWork"],
        platforms: ["facebook", "x", "google_business"],
        status: "published",
        mediaUrls: [],
        mediaType: "image",
        publishedAt: daysAgo(4),
        createdBy: "AI Studio",
        approvedBy: "Alex Rivera",
        aiGenerated: true,
        offerId: "off_hh",
        createdAt: daysAgo(6),
        updatedAt: daysAgo(4),
      },
      {
        id: "cnt_005",
        restaurantId: DEMO_RESTAURANT_ID,
        title: "Catering for Teams",
        body: "Feeding a team offsite? Our catering trays start at 10 guests — grilled chicken, seasonal salads, and cookies that disappear first. Same-day available before 10am orders.",
        hashtags: ["#CorporateCatering", "#OaklandBusiness", "#OfficeLunch"],
        platforms: ["linkedin", "email"],
        status: "draft",
        mediaUrls: [],
        mediaType: "none",
        createdBy: "Alex Rivera",
        aiGenerated: false,
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
      },
    ],
    offers: [
      {
        id: "off_brunch15",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Weekend Brunch 15% Off",
        code: "BRUNCH15",
        description: "15% off brunch checks Sat–Sun before 2pm. Dine-in only.",
        type: "percent",
        value: 15,
        channels: ["app", "pos", "social", "email"],
        status: "active",
        startsAt: daysAgo(7),
        endsAt: daysFrom(21),
        redemptions: 184,
        revenueAttributed: 12480,
        audience: "all",
        stackable: false,
        createdAt: daysAgo(10),
      },
      {
        id: "off_2xpoints",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Double Points Weekdays",
        code: "2XPOINTS",
        description: "2× loyalty points on entrées Mon–Thu.",
        type: "loyalty_boost",
        value: 2,
        channels: ["app", "pos", "email", "sms"],
        status: "scheduled",
        startsAt: daysFrom(1),
        endsAt: daysFrom(8),
        redemptions: 0,
        revenueAttributed: 0,
        audience: "loyalty",
        stackable: true,
        createdAt: daysAgo(1),
      },
      {
        id: "off_hh",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Downtown Happy Hour",
        code: "HH46",
        description: "$8 cocktails + half-off small plates 4–6pm weekdays.",
        type: "bundle",
        value: 0,
        channels: ["in_store", "pos", "social"],
        status: "active",
        startsAt: daysAgo(30),
        endsAt: daysFrom(60),
        redemptions: 920,
        revenueAttributed: 28700,
        audience: "all",
        stackable: false,
        createdAt: daysAgo(45),
      },
      {
        id: "off_welcome",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "New Guest Welcome",
        code: "WELCOME10",
        description: "$10 off first order $40+ for new loyalty members.",
        type: "fixed",
        value: 10,
        channels: ["app", "online", "email"],
        status: "active",
        startsAt: daysAgo(90),
        endsAt: daysFrom(90),
        minOrder: 40,
        maxRedemptions: 5000,
        redemptions: 612,
        revenueAttributed: 31400,
        audience: "new",
        stackable: false,
        createdAt: daysAgo(100),
      },
      {
        id: "off_bogo_apps",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "BOGO Apps Tuesday",
        code: "BOGOAPP",
        description: "Buy one appetizer, get one free (equal or lesser value) every Tuesday.",
        type: "bogo",
        value: 1,
        channels: ["pos", "in_store", "social"],
        status: "paused",
        startsAt: daysAgo(14),
        endsAt: daysFrom(30),
        redemptions: 76,
        revenueAttributed: 4200,
        audience: "all",
        stackable: false,
        createdAt: daysAgo(20),
      },
    ],
    customers: [
      {
        id: "cus_001",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Maya Chen",
        email: "maya.c@example.com",
        phone: "+1-510-555-0199",
        tier: "platinum",
        points: 4820,
        lifetimeSpend: 6240,
        visitCount: 47,
        lastVisitAt: daysAgo(2),
        tags: ["vip", "brunch", "wine"],
        source: "app",
        birthday: "1991-04-12",
        marketingOptIn: true,
        createdAt: daysAgo(400),
      },
      {
        id: "cus_002",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Sam Okonkwo",
        email: "sam.o@example.com",
        tier: "gold",
        points: 2100,
        lifetimeSpend: 2890,
        visitCount: 22,
        lastVisitAt: daysAgo(8),
        tags: ["catering", "corporate"],
        source: "online",
        marketingOptIn: true,
        createdAt: daysAgo(200),
      },
      {
        id: "cus_003",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Priya Nair",
        phone: "+1-415-555-0177",
        tier: "silver",
        points: 640,
        lifetimeSpend: 980,
        visitCount: 9,
        lastVisitAt: daysAgo(15),
        tags: ["happy-hour"],
        source: "pos",
        marketingOptIn: true,
        createdAt: daysAgo(90),
      },
      {
        id: "cus_004",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Chris Delgado",
        email: "chris.d@example.com",
        phone: "+1-510-555-0188",
        tier: "bronze",
        points: 120,
        lifetimeSpend: 210,
        visitCount: 2,
        lastVisitAt: daysAgo(40),
        tags: ["lapsed", "winback"],
        source: "walk_in",
        marketingOptIn: true,
        createdAt: daysAgo(50),
      },
      {
        id: "cus_005",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Elena Brooks",
        email: "elena.b@example.com",
        phone: "+1-510-555-0133",
        tier: "gold",
        points: 1880,
        lifetimeSpend: 2450,
        visitCount: 18,
        lastVisitAt: daysAgo(5),
        tags: ["family", "weekend"],
        source: "app",
        birthday: "1988-11-03",
        marketingOptIn: true,
        createdAt: daysAgo(180),
      },
      {
        id: "cus_006",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Jordan Park",
        email: "jordan.p@example.com",
        tier: "silver",
        points: 910,
        lifetimeSpend: 1320,
        visitCount: 11,
        lastVisitAt: daysAgo(3),
        tags: ["delivery"],
        source: "online",
        marketingOptIn: true,
        createdAt: daysAgo(110),
      },
    ],
    orders: generateOrders(),
    reviews: [
      {
        id: "rev_001",
        restaurantId: DEMO_RESTAURANT_ID,
        platform: "google",
        rating: 5,
        author: "Natalie R.",
        body: "Best brunch in Oakland. The lemon ricotta pancakes are unreal and service was warm without being hovering.",
        replied: true,
        replyBody: "Natalie — thank you! Those pancakes are a labor of love. See you next weekend?",
        sentiment: "positive",
        createdAt: daysAgo(1),
      },
      {
        id: "rev_002",
        restaurantId: DEMO_RESTAURANT_ID,
        platform: "yelp",
        rating: 4,
        author: "Marcus T.",
        body: "Solid happy hour. Cocktails are creative. Waited a bit for food on a Thursday but atmosphere made up for it.",
        replied: false,
        sentiment: "positive",
        createdAt: daysAgo(2),
      },
      {
        id: "rev_003",
        restaurantId: DEMO_RESTAURANT_ID,
        platform: "google",
        rating: 2,
        author: "Anon Guest",
        body: "Pasta was cold and our server disappeared for 20 minutes. Won't be back soon.",
        replied: false,
        sentiment: "negative",
        createdAt: daysAgo(1.5),
      },
      {
        id: "rev_004",
        restaurantId: DEMO_RESTAURANT_ID,
        platform: "doorDash",
        rating: 5,
        author: "Aisha K.",
        body: "Delivery arrived hot, packaging was thoughtful. The seasonal salad slapped.",
        replied: true,
        replyBody: "Aisha, glad it traveled well — packaging is something we obsess over!",
        sentiment: "positive",
        createdAt: daysAgo(4),
      },
      {
        id: "rev_005",
        restaurantId: DEMO_RESTAURANT_ID,
        platform: "tripadvisor",
        rating: 3,
        author: "Tom H.",
        body: "Nice vibe, average entrees for the price. Desserts saved the night.",
        replied: false,
        sentiment: "neutral",
        createdAt: daysAgo(6),
      },
    ],
    integrations: [
      {
        id: "int_meta",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "meta",
        category: "ads",
        status: "disconnected",
        configHint: "Connect Meta Business Manager + Ad Account for Facebook/Instagram ads.",
        envKeys: ["META_APP_ID", "META_APP_SECRET", "META_ACCESS_TOKEN", "META_AD_ACCOUNT_ID"],
      },
      {
        id: "int_ig",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "instagram",
        category: "social",
        status: "disconnected",
        configHint: "Instagram Graph API via Meta — publish feed, reels, stories.",
        envKeys: ["META_ACCESS_TOKEN", "INSTAGRAM_BUSINESS_ACCOUNT_ID"],
      },
      {
        id: "int_fb",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "facebook",
        category: "social",
        status: "disconnected",
        configHint: "Facebook Pages API for organic posts and page insights.",
        envKeys: ["META_ACCESS_TOKEN", "FACEBOOK_PAGE_ID"],
      },
      {
        id: "int_google_ads",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "google_ads",
        category: "ads",
        status: "disconnected",
        configHint: "Google Ads API for search/local campaigns and performance max.",
        envKeys: ["GOOGLE_ADS_CLIENT_ID", "GOOGLE_ADS_CLIENT_SECRET", "GOOGLE_ADS_REFRESH_TOKEN", "GOOGLE_ADS_CUSTOMER_ID"],
      },
      {
        id: "int_tiktok",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "tiktok",
        category: "social",
        status: "disconnected",
        configHint: "TikTok Content Posting API for short-form video.",
        envKeys: ["TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET", "TIKTOK_ACCESS_TOKEN"],
      },
      {
        id: "int_creatomate",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "creatomate",
        category: "video",
        status: "disconnected",
        configHint: "Template-based video render for Reels/TikTok/ads.",
        envKeys: ["CREATOMATE_API_KEY", "CREATOMATE_TEMPLATE_ID"],
      },
      {
        id: "int_shotstack",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "shotstack",
        category: "video",
        status: "disconnected",
        configHint: "Alternative video edit/render pipeline (Shotstack Edit API).",
        envKeys: ["SHOTSTACK_API_KEY", "SHOTSTACK_ENV"],
      },
      {
        id: "int_toast",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "toast",
        category: "pos",
        status: "disconnected",
        configHint: "Toast POS orders, menu, and guest data webhooks.",
        envKeys: ["TOAST_CLIENT_ID", "TOAST_CLIENT_SECRET", "TOAST_RESTAURANT_GUID"],
      },
      {
        id: "int_square",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "square",
        category: "pos",
        status: "disconnected",
        configHint: "Square Orders + Customers APIs and payment webhooks.",
        envKeys: ["SQUARE_ACCESS_TOKEN", "SQUARE_LOCATION_ID", "SQUARE_ENV"],
      },
      {
        id: "int_clover",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "clover",
        category: "pos",
        status: "disconnected",
        configHint: "Clover REST Pay and merchant orders.",
        envKeys: ["CLOVER_API_TOKEN", "CLOVER_MERCHANT_ID"],
      },
      {
        id: "int_openai",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "openai",
        category: "ai",
        status: "disconnected",
        configHint: "Optional OpenAI key for live caption generation. Demo mode works without it.",
        envKeys: ["OPENAI_API_KEY", "OPENAI_MODEL"],
      },
      {
        id: "int_twilio",
        restaurantId: DEMO_RESTAURANT_ID,
        provider: "twilio",
        category: "comms",
        status: "disconnected",
        configHint: "SMS loyalty + offer blasts.",
        envKeys: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_FROM_NUMBER"],
      },
    ],
    notifications: [
      {
        id: "ntf_001",
        restaurantId: DEMO_RESTAURANT_ID,
        type: "approval",
        title: "Content awaiting approval",
        body: "“Loyalty Double Points” is ready for review.",
        read: false,
        href: "/approvals",
        createdAt: daysAgo(0.4),
      },
      {
        id: "ntf_002",
        restaurantId: DEMO_RESTAURANT_ID,
        type: "review",
        title: "New 2★ Google review",
        body: "A guest mentioned cold pasta — reply recommended within 24h.",
        read: false,
        href: "/reviews",
        createdAt: daysAgo(1.4),
      },
      {
        id: "ntf_003",
        restaurantId: DEMO_RESTAURANT_ID,
        type: "campaign",
        title: "Happy Hour offer pacing strong",
        body: "HH46 attributed $28.7k — consider extending end date.",
        read: true,
        href: "/offers",
        createdAt: daysAgo(3),
      },
      {
        id: "ntf_004",
        restaurantId: DEMO_RESTAURANT_ID,
        type: "loyalty",
        title: "Maya Chen hit Platinum",
        body: "Trigger VIP welcome perk and personal thank-you.",
        read: false,
        href: "/customers",
        createdAt: daysAgo(2),
      },
    ],
    auditLogs: [
      {
        id: "aud_001",
        restaurantId: DEMO_RESTAURANT_ID,
        actor: "Alex Rivera",
        action: "content.approved",
        entityType: "content",
        entityId: "cnt_003",
        createdAt: daysAgo(2),
      },
      {
        id: "aud_002",
        restaurantId: DEMO_RESTAURANT_ID,
        actor: "AI Studio",
        action: "content.generated",
        entityType: "content",
        entityId: "cnt_002",
        meta: { platforms: ["instagram", "email", "sms"] },
        createdAt: daysAgo(0.5),
      },
      {
        id: "aud_003",
        restaurantId: DEMO_RESTAURANT_ID,
        actor: "system",
        action: "offer.activated",
        entityType: "offer",
        entityId: "off_hh",
        createdAt: daysAgo(30),
      },
      {
        id: "aud_004",
        restaurantId: DEMO_RESTAURANT_ID,
        actor: "Alex Rivera",
        action: "content.published",
        entityType: "content",
        entityId: "cnt_004",
        createdAt: daysAgo(4),
      },
      {
        id: "aud_005",
        restaurantId: DEMO_RESTAURANT_ID,
        actor: "system",
        action: "order.ingested",
        entityType: "order",
        entityId: "ord_demo_last",
        meta: { source: "demo_pos" },
        createdAt: daysAgo(0.1),
      },
    ],
    campaigns: [
      {
        id: "cmp_001",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Spring Brunch Awareness",
        objective: "traffic",
        status: "active",
        budget: 2500,
        spent: 1180,
        channels: ["meta", "google"],
        startAt: daysAgo(14),
        endAt: daysFrom(16),
        metrics: { impressions: 142000, clicks: 4800, conversions: 312, roas: 4.2 },
      },
      {
        id: "cmp_002",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Loyalty Win-back SMS",
        objective: "loyalty",
        status: "active",
        budget: 400,
        spent: 180,
        channels: ["sms", "email"],
        startAt: daysAgo(7),
        endAt: daysFrom(7),
        metrics: { impressions: 2200, clicks: 640, conversions: 88, roas: 6.1 },
      },
      {
        id: "cmp_003",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Catering Lead Gen",
        objective: "conversions",
        status: "paused",
        budget: 1500,
        spent: 920,
        channels: ["linkedin", "google"],
        startAt: daysAgo(40),
        endAt: daysAgo(5),
        metrics: { impressions: 38000, clicks: 1100, conversions: 42, roas: 3.4 },
      },
    ],
    ads: [
      {
        id: "ad_meta",
        restaurantId: DEMO_RESTAURANT_ID,
        platform: "meta",
        name: "Meta Ads — GGB",
        status: "disconnected",
        spend30d: 980,
        impressions30d: 110000,
        clicks30d: 3600,
        conversions30d: 240,
      },
      {
        id: "ad_google",
        restaurantId: DEMO_RESTAURANT_ID,
        platform: "google",
        name: "Google Ads — GGB",
        status: "disconnected",
        spend30d: 720,
        impressions30d: 54000,
        clicks30d: 2100,
        conversions30d: 160,
      },
    ],

    media: [
      {
        id: "media_brunch",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Brunch hero",
        mimeType: "image/svg+xml",
        size: 2400,
        url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='800' height='1000' viewBox='0 0 800 1000'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='#fb923c'/><stop offset='1' stop-color='#9a3412'/></linearGradient></defs><rect width='800' height='1000' fill='url(#g)'/><circle cx='620' cy='180' r='90' fill='#fde68a' opacity='.85'/><text x='48' y='820' fill='white' font-family='system-ui' font-size='54' font-weight='700'>Weekend Brunch</text><text x='48' y='880' fill='white' font-family='system-ui' font-size='28' opacity='.9'>Lemon ricotta · Oakland</text></svg>`),
        kind: "image",
        width: 800,
        height: 1000,
        source: "stock",
        tags: ["brunch", "hero"],
        createdAt: daysAgo(10),
      },
      {
        id: "media_pasta",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Seasonal pasta",
        mimeType: "image/svg+xml",
        size: 2100,
        url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='1080' height='1080'><defs><linearGradient id='g' x1='0' y1='1' x2='1' y2='0'><stop stop-color='#0f172a'/><stop offset='1' stop-color='#c2410c'/></linearGradient></defs><rect width='1080' height='1080' fill='url(#g)'/><rect x='80' y='80' width='920' height='920' rx='48' fill='none' stroke='white' stroke-opacity='.25' stroke-width='4'/><text x='120' y='520' fill='white' font-family='system-ui' font-size='64' font-weight='700'>Pappardelle</text><text x='120' y='590' fill='#fdba74' font-family='system-ui' font-size='32'>brown butter · sage</text></svg>`),
        kind: "image",
        width: 1080,
        height: 1080,
        source: "stock",
        tags: ["dinner", "pasta"],
        createdAt: daysAgo(6),
      },
      {
        id: "media_hh",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Happy hour cocktails",
        mimeType: "image/svg+xml",
        size: 1900,
        url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='1080' height='1350'><rect width='1080' height='1350' fill='#1e293b'/><circle cx='540' cy='520' r='220' fill='#ea580c' opacity='.9'/><circle cx='540' cy='520' r='140' fill='#ffedd5'/><text x='540' y='980' text-anchor='middle' fill='white' font-family='system-ui' font-size='56' font-weight='700'>Happy Hour</text><text x='540' y='1050' text-anchor='middle' fill='#94a3b8' font-family='system-ui' font-size='28'>4–6pm · $8 cocktails</text></svg>`),
        kind: "image",
        width: 1080,
        height: 1350,
        source: "stock",
        tags: ["happy-hour", "drinks"],
        createdAt: daysAgo(20),
      },
    ],
    blasts: [
      {
        id: "blast_001",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "Lapsed guest win-back",
        channel: "sms",
        segment: "lapsed",
        body: "Golden Gate Bistro: We miss you. Here's $10 off $40+ this week — code WELCOME10. Reply STOP to opt out.",
        offerCode: "WELCOME10",
        offerId: "off_welcome",
        status: "sent",
        audienceCount: 1,
        sentCount: 1,
        sentAt: daysAgo(5),
        demo: true,
        createdAt: daysAgo(5),
      },
      {
        id: "blast_002",
        restaurantId: DEMO_RESTAURANT_ID,
        name: "VIP double points preview",
        channel: "email",
        segment: "vip",
        subject: "Platinum perk: 2× points next week",
        body: "Hi {{first_name}},\n\nAs a Platinum guest, you get first look: 2× points Mon–Thu on entrées. Code 2XPOINTS in the app.\n\nSee you soon,\nGolden Gate Bistro",
        offerCode: "2XPOINTS",
        offerId: "off_2xpoints",
        status: "draft",
        audienceCount: 1,
        sentCount: 0,
        demo: true,
        createdAt: daysAgo(1),
      },
    ],
    analytics: [
      {
        restaurantId: DEMO_RESTAURANT_ID,
        period: "last_30_days",
        revenue: 186400,
        orders: 4120,
        avgTicket: 45.24,
        newCustomers: 318,
        loyaltyRedemptions: 640,
        contentPublished: 28,
        adSpend: 1700,
        adRoas: 4.6,
        reviewAvg: 4.3,
        reviewCount: 86,
        topItems: [
          { name: "Lemon Ricotta Pancakes", qty: 620, revenue: 9300 },
          { name: "Seasonal Pappardelle", qty: 410, revenue: 9020 },
          { name: "Smoked Salmon Board", qty: 380, revenue: 8360 },
          { name: "House Burger", qty: 540, revenue: 9180 },
          { name: "Cold Brew Flight", qty: 290, revenue: 2610 },
        ],
        revenueByDay: Array.from({ length: 14 }).map((_, i) => {
          const d = new Date(now - (13 - i) * 86400000);
          const base = 5500 + (i % 5) * 400 + (i > 10 ? 1200 : 0);
          return {
            date: d.toISOString().slice(0, 10),
            revenue: base + Math.round(Math.sin(i) * 300),
            orders: Math.round(base / 45),
          };
        }),
        channelMix: [
          { channel: "Dine-in", revenue: 98000, pct: 52.6 },
          { channel: "Takeout", revenue: 32000, pct: 17.2 },
          { channel: "Delivery", revenue: 28000, pct: 15.0 },
          { channel: "App", revenue: 18400, pct: 9.9 },
          { channel: "Catering", revenue: 10000, pct: 5.4 },
        ],
      },
    ],
  };
}

function generateOrders() {
  const channels = ["dine_in", "takeout", "delivery", "app", "kiosk"] as const;
  const items = [
    { name: "Lemon Ricotta Pancakes", price: 15 },
    { name: "Seasonal Pappardelle", price: 22 },
    { name: "House Burger", price: 17 },
    { name: "Smoked Salmon Board", price: 22 },
    { name: "Caesar Salad", price: 14 },
    { name: "Cold Brew", price: 5 },
    { name: "Tiramisu", price: 11 },
  ];
  const orders = [];
  for (let i = 0; i < 24; i++) {
    const nItems = 1 + (i % 3);
    const line = Array.from({ length: nItems }).map((_, j) => {
      const it = items[(i + j) % items.length];
      const qty = 1 + ((i + j) % 2);
      return { name: it.name, qty, price: it.price };
    });
    const subtotal = line.reduce((s, l) => s + l.price * l.qty, 0);
    const tax = Math.round(subtotal * 0.1025 * 100) / 100;
    const tip = i % 4 === 0 ? Math.round(subtotal * 0.18 * 100) / 100 : 0;
    orders.push({
      id: i === 0 ? "ord_demo_last" : `ord_${String(i).padStart(3, "0")}`,
      restaurantId: DEMO_RESTAURANT_ID,
      externalId: `POS-${10000 + i}`,
      channel: channels[i % channels.length],
      posSource: "demo_pos",
      customerId: i % 3 === 0 ? `cus_00${(i % 6) + 1}` : undefined,
      customerName: i % 3 === 0 ? undefined : undefined,
      items: line,
      subtotal,
      tax,
      tip,
      total: Math.round((subtotal + tax + tip) * 100) / 100,
      offerCode: i % 5 === 0 ? "BRUNCH15" : i % 7 === 0 ? "WELCOME10" : undefined,
      status: "completed" as const,
      orderedAt: daysAgo(i * 0.3),
    });
  }
  return orders;
}
