import { z } from 'zod';
import { AppError } from './context';
const text=z.string().trim().min(1).max(10000),short=z.string().trim().min(1).max(200);
const money=z.number().finite().min(0).max(100000000);
const strings=z.array(z.string().max(200)).max(30);
const url=z.string().max(3500000).refine(v=>/^\/api\/media\/file\?id=media_[a-zA-Z0-9-]+$/.test(v)||/^https:\/\//.test(v)||/^data:(image\/(png|jpeg|webp|gif)|video\/(mp4|webm));base64,/.test(v),'Invalid media URL');
const date=z.string().refine(v=>Number.isFinite(Date.parse(v)),'Invalid date');
const platform=z.enum(['instagram','facebook','tiktok','x','linkedin','google_business','email','sms']);
export const contentInput=z.object({title:short,body:text,restaurantId:short.optional(),hashtags:strings.optional(),platforms:z.array(platform).min(1).max(8).optional(),status:z.enum(['draft','pending_approval','approved','scheduled','published','rejected','failed']).optional(),mediaUrls:z.array(url).max(10).optional(),mediaType:z.enum(['image','video','carousel','none']).optional(),scheduledAt:date.optional(),createdBy:short.optional(),aiGenerated:z.boolean().optional(),campaignId:short.optional(),offerId:short.optional()}).strict();
export const offerInput=z.object({name:short,code:z.string().trim().regex(/^[a-zA-Z0-9_-]{1,50}$/),restaurantId:short.optional(),description:z.string().max(10000).optional(),type:z.enum(['percent','fixed','bogo','free_item','bundle','loyalty_boost']).optional(),value:money.optional(),channels:z.array(z.enum(['app','pos','online','social','email','sms','in_store'])).max(7).optional(),status:z.enum(['draft','active','scheduled','paused','expired']).optional(),startsAt:date.optional(),endsAt:date.optional(),minOrder:money.optional(),maxRedemptions:z.number().int().positive().optional(),audience:z.enum(['all','new','loyalty','lapsed','vip']).optional(),stackable:z.boolean().optional()}).strict();
export const customerInput=z.object({name:short,restaurantId:short.optional(),email:z.union([z.email(),z.literal('')]).optional(),phone:z.string().max(30).optional(),tier:z.enum(['bronze','silver','gold','platinum']).optional(),points:z.number().int().nonnegative().max(100000000).optional(),lifetimeSpend:money.optional(),visitCount:z.number().int().nonnegative().optional(),lastVisitAt:date.optional(),tags:strings.optional(),source:z.enum(['pos','online','app','walk_in','import']).optional(),birthday:z.union([date,z.literal('')]).optional(),marketingOptIn:z.boolean().optional()}).strict();
export const orderInput=z.object({total:money,restaurantId:short.optional(),externalId:short.optional(),channel:z.enum(['dine_in','takeout','delivery','app','kiosk','catering']).optional(),posSource:short.optional(),customerId:short.optional(),customerName:short.optional(),items:z.array(z.object({name:short,qty:z.number().int().positive().max(10000),price:money}).strict()).max(200).optional(),subtotal:money.optional(),tax:money.optional(),tip:money.optional(),offerCode:short.optional(),status:z.enum(['completed','refunded','cancelled']).optional(),orderedAt:date.optional()}).strict();
export function validate(schema:z.ZodType,input:unknown){const parsed=schema.safeParse(input);if(!parsed.success)throw new AppError(parsed.error.issues[0]?.message||'Invalid input');}
